# Generated by Django 5.2.5 on 2025-11-20 19:28

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("slug", models.SlugField(blank=True, max_length=120)),
                (
                    "nome_normalizado",
                    models.CharField(db_index=True, editable=False, max_length=120),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categorias",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Despesa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "emitente_nome",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Emitente / Loja",
                    ),
                ),
                (
                    "emitente_cnpj",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="CNPJ do Emitente",
                    ),
                ),
                (
                    "descricao",
                    models.CharField(max_length=200, verbose_name="Descrição Resumida"),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Valor Total"
                    ),
                ),
                (
                    "qtd_total_itens",
                    models.IntegerField(default=0, verbose_name="Qtd. Itens"),
                ),
                (
                    "forma_pagamento",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Forma de Pagamento",
                    ),
                ),
                ("data", models.DateField(default=django.utils.timezone.localdate)),
                ("observacoes", models.TextField(blank=True, null=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="despesas",
                        to="despesas.categoria",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="despesas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Despesa",
                "verbose_name_plural": "Despesas",
                "ordering": ["-data", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ItemDespesa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("codigo", models.CharField(blank=True, max_length=50, null=True)),
                ("quantidade", models.DecimalField(decimal_places=3, max_digits=10)),
                ("unidade", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "valor_unitario",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("valor_total", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "despesa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="despesas.despesa",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("foto_url", models.URLField(blank=True, null=True)),
                ("moeda", models.CharField(default="BRL", max_length=3)),
                (
                    "limite_mensal",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfil",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="categoria",
            constraint=models.UniqueConstraint(
                fields=("user", "nome_normalizado"),
                name="uniq_categoria_por_usuario_normalizada",
            ),
        ),
    ]
