# Generated by Django 5.2.5 on 2025-10-23 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE despesas_despesa RENAME COLUMN usuario_id TO user_id;",
            reverse_sql="ALTER TABLE despesas_despesa RENAME COLUMN user_id TO usuario_id;"
        ),
    ]
