# Generated by Django 5.2.5 on 2025-11-20 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("despesas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="despesa",
            name="descricao",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Descrição Resumida"
            ),
        ),
        migrations.AlterField(
            model_name="despesa",
            name="emitente_nome",
            field=models.CharField(max_length=200, verbose_name="Emitente / Loja"),
        ),
    ]
