# Generated by Django 5.2.5 on 2025-11-20 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("despesas", "0003_alter_despesa_emitente_nome"),
    ]

    operations = [
        migrations.AlterField(
            model_name="despesa",
            name="emitente_nome",
            field=models.CharField(
                default="Não Informado", max_length=200, verbose_name="Emitente / Loja"
            ),
        ),
        migrations.AlterField(
            model_name="despesa",
            name="forma_pagamento",
            field=models.CharField(
                choices=[
                    ("DINHEIRO", "Dinheiro"),
                    ("CREDITO", "Cartão de Crédito"),
                    ("DEBITO", "Cartão de Débito"),
                    ("PIX", "Pix"),
                    ("BOLETO", "Boleto"),
                    ("VALE_ALIMENTACAO", "Vale Alimentação"),
                    ("VALE_REFEICAO", "Vale Refeição"),
                    ("OUTROS", "Outros"),
                ],
                default="OUTROS",
                max_length=20,
                verbose_name="Forma de Pagamento",
            ),
        ),
    ]
