# Generated by Django 5.2.5 on 2025-11-20 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("despesas", "0004_alter_despesa_emitente_nome_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="despesa",
            name="emitente_nome",
            field=models.CharField(max_length=200, verbose_name="Emitente / Loja"),
        ),
    ]
