# Generated by Django 5.2.5 on 2025-11-20 22:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("despesas", "0005_alter_despesa_emitente_nome"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Receita",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descricao",
                    models.CharField(max_length=200, verbose_name="Descrição"),
                ),
                (
                    "valor_bruto",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Valor Bruto (R$)"
                    ),
                ),
                (
                    "valor_investimento",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Investimentos / Retenções (R$)",
                    ),
                ),
                (
                    "data",
                    models.DateField(
                        default=django.utils.timezone.localdate,
                        verbose_name="Data de Recebimento",
                    ),
                ),
                ("observacoes", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receitas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Receita",
                "verbose_name_plural": "Receitas",
                "ordering": ["-data", "-id"],
            },
        ),
    ]
