# Generated by Django 5.2.5 on 2025-11-20 23:07

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("despesas", "0006_receita"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="investimento_fixo",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                max_digits=10,
                verbose_name="Investimento Mensal Fixo (R$)",
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="renda_fixa",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                max_digits=10,
                verbose_name="Renda Mensal Fixa (R$)",
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="limite_mensal",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                max_digits=10,
                verbose_name="Teto de Gastos",
            ),
        ),
    ]
