# Generated by Django 5.2.5 on 2025-11-21 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("despesas", "0007_usuario_investimento_fixo_usuario_renda_fixa_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoria",
            name="orcamento_mensal",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Orçamento Mensal (R$)",
            ),
        ),
        migrations.AddField(
            model_name="despesa",
            name="tipo",
            field=models.CharField(
                choices=[("FIXA", "Fixa"), ("VARIAVEL", "Variável")],
                default="VARIAVEL",
                max_length=10,
                verbose_name="Tipo de Despesa",
            ),
        ),
    ]
