# Generated by Django 5.2.5 on 2025-11-21 23:56

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("despesas", "0008_categoria_orcamento_mensal_despesa_tipo"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="limite_aviso",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="Valor para disparar notificações de aviso.",
                max_digits=10,
                verbose_name="Alerta de Gastos (Soft Cap)",
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="limite_mensal",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                max_digits=10,
                verbose_name="Teto Máximo (Hard Cap)",
            ),
        ),
    ]
