# Generated by Django 5.2.5 on 2025-11-22 14:17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("despesas", "0009_usuario_limite_aviso_alter_usuario_limite_mensal"),
    ]

    operations = [
        migrations.AddField(
            model_name="despesa",
            name="desconto",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                max_digits=10,
                verbose_name="Descontos",
            ),
        ),
        migrations.AddField(
            model_name="despesa",
            name="parcela_atual",
            field=models.IntegerField(default=1, verbose_name="Parcela Atual"),
        ),
        migrations.AddField(
            model_name="despesa",
            name="total_parcelas",
            field=models.IntegerField(default=1, verbose_name="Total Parcelas"),
        ),
        migrations.AlterField(
            model_name="despesa",
            name="valor",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Valor a Pagar (Líquido)"
            ),
        ),
    ]
