# Generated by Django 5.2.5 on 2025-11-22 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("despesas", "0010_despesa_desconto_despesa_parcela_atual_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="despesa",
            name="valor_total_compra",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Valor Total da Compra",
            ),
        ),
        migrations.AlterField(
            model_name="despesa",
            name="valor",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                verbose_name="Valor da Parcela / Líquido",
            ),
        ),
    ]
