# Generated by Django 5.1.3 on 2025-11-27 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("despesas", "0011_despesa_valor_total_compra_alter_despesa_valor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="despesa",
            name="forma_pagamento",
            field=models.CharField(
                choices=[
                    ("DINHEIRO", "Dinheiro"),
                    ("CREDITO", "Cartão de Crédito"),
                    ("DEBITO", "Cartão de Débito"),
                    ("PIX", "Pix"),
                    ("BOLETO", "Boleto"),
                    ("VALE_ALIMENTACAO", "Vale Alimentação"),
                    ("VALE_REFEICAO", "Vale Refeição"),
                    ("OUTROS", "Outros"),
                ],
                max_length=20,
                verbose_name="Forma de Pagamento",
            ),
        ),
    ]
