# Generated by Django 5.1.3 on 2026-01-06 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("despesas", "0012_alter_despesa_forma_pagamento"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usuario",
            name="limite_aviso",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="limite_mensal",
        ),
        migrations.AddField(
            model_name="usuario",
            name="alertas_email_ativos",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="AlertaOrcamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ano", models.IntegerField()),
                ("mes", models.IntegerField()),
                ("percentual", models.PositiveIntegerField()),
                ("enviado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="despesas.usuario",
                    ),
                ),
            ],
            options={
                "unique_together": {("perfil", "ano", "mes", "percentual")},
            },
        ),
    ]
