# Generated by Django 5.1.3 on 2026-01-16 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("despesas", "0013_remove_usuario_limite_aviso_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usuario",
            name="investimento_fixo",
        ),
    ]
