# Generated by Django 5.1.3 on 2026-01-16 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("despesas", "0014_remove_usuario_investimento_fixo"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="limiares_alerta",
            field=models.CharField(
                default="80, 90, 100",
                help_text="Separe as porcentagens por vírgula. Ex: 80, 90, 100",
                max_length=50,
                verbose_name="Porcentagens de alerta",
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="alertas_email_ativos",
            field=models.BooleanField(
                default=True, verbose_name="Receber alertas por e-mail"
            ),
        ),
    ]
