# Generated by Django 5.1.3 on 2026-01-17 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("despesas", "0015_usuario_limiares_alerta_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="receita",
            name="valor_investimento",
        ),
    ]
