# Generated by Django 5.1.3 on 2026-01-17 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("despesas", "0016_remove_receita_valor_investimento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemdespesa",
            name="quantidade",
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
